INSERT INTO elemento (id, nomElemento)
VALUES (1, 'Fuego'),
    (2, 'Agua'),
    (3, 'Aire'),
    (4, 'Tierra');
    
INSERT INTO cualidad (id, nomAdjetivo, descripcion, ELEMENTOid)
VALUES (1, 'acepta riesgos', 'abc', 1),
    (2, 'agresivo/a', 'abc', 1),
    (3, 'atrevido/a', 'abc', 1),
    (4, 'audaz', 'abc', 1),
    (5, 'auto suficiente', 'abc', 1),
    (6, 'competitivo/a', 'abc', 1),
    (7, 'tenaz', 'abc', 1),
    (8, 'decidido/a', 'abc', 1),
    (9, 'decisivo/a', 'abc', 1),
    (10, 'valeroso/a', 'abc', 1),
    (11, 'vigoroso/a', 'abc', 1),
    (12, 'directo/a', 'abc', 1),
    (13, 'enérgico/a', 'abc', 1),
    (14, 'osado/a', 'abc', 1),
    (15, 'dominante', 'abc', 1),
    (16, 'habla directo', 'abc', 1),
    (17, 'ideas firmes', 'abc', 1),
    (18, 'impaciente', 'abc', 1),
    (19, 'exigente', 'abc', 1),
    (20, 'independiente', 'abc', 1),
    (21, 'rápido/a', 'abc', 1),
    (22, 'inquieto/a', 'abc', 1),
    (23, 'insistente', 'abc', 1),
    (24, 'resuelto/a', 'abc', 1),
    (25, 'franco/a', 'abc', 1),
    (26, 'le agrada discutir', 'abc', 1),
    (27, 'persistente', 'abc', 1),
    (28, 'pionero, iniciador', 'abc', 1),
    (29, 'adaptable', 'abc', 2),
    (30, 'amable', 'abc', 2),
    (31, 'ameno/a', 'abc', 2),
    (32, 'amistoso/a', 'abc', 2),
    (33, 'bondadoso/a', 'abc', 2),
    (34, 'calmado/a', 'abc', 2),
    (35, 'apacible', 'abc', 2),
    (36, 'colaborador', 'abc', 2),
    (37, 'comedido/a', 'abc', 2),
    (38, 'atento/a', 'abc', 2),
    (39, 'complaciente', 'abc', 2),
    (40, 'comprensivo/a', 'abc', 2),
    (41, 'considerado/a', 'abc', 2),
    (42, 'constante', 'abc', 2),
    (43, 'contento/a', 'abc', 2),
    (44, 'sensible', 'abc', 2),
    (45, 'tolerante', 'abc', 2),
    (46, 'tranquilo/a', 'abc', 2),
    (47, 'ecuánime', 'abc', 2),
    (48, 'obediente', 'abc', 2),
    (49, 'leal', 'abc', 2),
    (50, 'paciente', 'abc', 2),
    (51, 'pacifico', 'abc', 2),
    (52, 'generoso/a', 'abc', 2),
    (53, 'gentil', 'abc', 2),
    (54, 'moderado/a', 'abc', 2),
    (55, 'alegre', 'abc', 3),
    (56, 'alentador/a', 'abc', 3),
    (57, 'amigable', 'abc', 3),
    (58, 'anima a los demás', 'abc', 3),
    (59, 'animado/a', 'abc', 3),
    (60, 'cautivador/a', 'abc', 3),
    (61, 'comunicativo/a', 'abc', 3),
    (62, 'sociable', 'abc', 3),
    (63, 'vivaz', 'abc', 3),
    (64, 'de trato fácil', 'abc', 3),
    (65, 'elocuente', 'abc', 3),
    (66, 'encantador/a', 'abc', 3),
    (67, 'desenvuelto/a', 'abc', 3),
    (68, 'impetuoso/a', 'abc', 3),
    (69, 'impulsivo/a', 'abc', 3),
    (70, 'promotor/a', 'abc', 3),
    (71, 'entusiasta', 'abc', 3),
    (72, 'espontáneo/a', 'abc', 3),
    (73, 'estimulante', 'abc', 3),
    (74, 'expresivo/a', 'abc', 3),
    (75, 'extrovertido/a', 'abc', 3),
    (76, 'receptivo/a', 'abc', 3),
    (77, 'ingenioso/a', 'abc', 3),
    (78, 'popular', 'abc', 3),
    (79, 'jovial', 'abc', 3),
    (80, 'analítico/a', 'abc', 4),
    (81, 'apego a normas', 'abc', 4),
    (82, 'cauteloso/a', 'abc', 4),
    (83, 'cauto/a', 'abc', 4),
    (84, 'certero/a', 'abc', 4),
    (85, 'concienzudo/a', 'abc', 4),
    (86, 'controlado/a', 'abc', 4),
    (87, 'cuida los detalles', 'abc', 4),
    (88, 'cuidadoso/a', 'abc', 4),
    (89, 'sistemático/a', 'abc', 4),
    (90, 'discerniente', 'abc', 4),
    (91, 'discreto/a', 'abc', 4),
    (92, 'reflexivo/a', 'abc', 4),
    (93, 'reservado/a', 'abc', 4),
    (94, 'preciso/a', 'abc', 4),
    (95, 'prevenido/a', 'abc', 4),
    (96, 'evaluador/a', 'abc', 4),
    (97, 'prudente', 'abc', 4),
    (98, 'lógico/a', 'abc', 4),
    (99, 'meticuloso/a', 'abc', 4),
    (100, 'metódico/a', 'abc', 4),
    (101, 'perceptivo/a', 'abc', 4),
    (102, 'perfeccionista', 'abc', 4),
    (103, 'investigador/a', 'abc', 4),
    (104, 'sagaz', 'abc', 4),
    (105, 'precavido/a', 'abc', 4);