CREATE TABLE PARTICIPANTE (
    id int(10) NOT NULL AUTO_INCREMENT,
    nombres varchar(255) NOT NULL,
    fecha_nacimiento date NOT NULL,
    telefono varchar(255) NOT NULL,
    correo varchar(255) NOT NULL,
    fecha_registro timestamp NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE ELEMENTO (
    id int(10) NOT NULL AUTO_INCREMENT,
    nomElemento varchar(15) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE CUALIDAD (
    id int(10) NOT NULL AUTO_INCREMENT,
    nomAdjetivo varchar(25) NOT NULL,
    descripcion text NOT NULL,
    ELEMENTOid int(10) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE GRUPO (
    id int(10) NOT NULL AUTO_INCREMENT,
    nomgrupo varchar(255),
    PRIMARY KEY (id)
);
CREATE TABLE ADMINISTRADOR (
    id int(11) NOT NULL AUTO_INCREMENT,
    nombres_completos varchar(255) NOT NULL,
    usuario varchar(255) NOT NULL,
    clave varchar(255) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE SELECCION (
    PARTICIPANTEid int(10) NOT NULL,
    CUALIDADid int(10) NOT NULL,
    estado tinyint(3) NOT NULL,
    PRIMARY KEY (PARTICIPANTEid, CUALIDADid)
);
CREATE TABLE AGRUPACION (
    GRUPOid int(10) NOT NULL,
    CUALIDADid int(10) NOT NULL,
    PRIMARY KEY (GRUPOid, CUALIDADid)
);
CREATE TABLE EMPRESA (
    id int(11) NOT NULL AUTO_INCREMENT,
    img_logo longblob NOT NULL,
    img_icono longblob NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE CUALIDAD
ADD CONSTRAINT FKCUALIDAD728706 FOREIGN KEY (ELEMENTOid) REFERENCES ELEMENTO (id);
ALTER TABLE SELECCION
ADD CONSTRAINT FKSELECCION321704 FOREIGN KEY (PARTICIPANTEid) REFERENCES PARTICIPANTE (id);
ALTER TABLE SELECCION
ADD CONSTRAINT FKSELECCION809300 FOREIGN KEY (CUALIDADid) REFERENCES CUALIDAD (id);
ALTER TABLE AGRUPACION
ADD CONSTRAINT FKAGRUPACION429682 FOREIGN KEY (GRUPOid) REFERENCES GRUPO (id);
ALTER TABLE AGRUPACION
ADD CONSTRAINT FKAGRUPACION321689 FOREIGN KEY (CUALIDADid) REFERENCES CUALIDAD (id);